x-shared-env: &shared-api-worker-env

services:
  api:
    build: 
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app/api
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      # Startup mode, 'api' starts the API server.
      MODE: api
    env_file:
      - ./.env
    depends_on:
      - redis
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - ./volumes/app/storage:/app/api/storage

  redis:
    image: redis:6-alpine
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD:-difyai123456}
    volumes:
      # Mount the redis data directory to the container.
      - ./volumes/redis/data:/data
    # Set the redis password when startup redis server.
    command: redis-server --requirepass ${REDIS_PASSWORD:-difyai123456}
    # command: redis-server --requirepass ${REDIS_PASSWORD:-difyai123456} --dir /data --dbfilename dump.rdb
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]

  worker:
    build: 
      context: ../api
      dockerfile: Dockerfile
    environment:
      <<: *shared-api-worker-env
      CELERY_LOG_FILE: /app/worker/logs/celery.log
      CELERY_LOG_DIR: /app/worker/logs
      MODE: worker
    command: celery -A src.celery_app:app worker --loglevel=info
    env_file:
      - ./.env
    depends_on:
      - redis
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - ./volumes/app/storage:/app/api/storage
      - ./volumes/worker/logs:/app/worker/logs
  beat:
      build: 
        context: ../api
        dockerfile: Dockerfile
      environment:
        <<: *shared-api-worker-env
        CELERY_LOG_FILE: /app/beat/logs/celerybeat.log
        CELERY_LOG_DIR: /app/beat/logs
        MODE: beat
      command: celery -A src.celery_app:app beat --loglevel=info
      env_file:
        - ./.env
      depends_on:
        - redis
      volumes:
        # Mount the storage directory to the container, for storing user files.
        - ./volumes/app/storage:/app/api/storage
        - ./volumes/beat/logs:/app/beat/logs

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      # 挂载初始化脚本目录
      - ./mysql/init:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

